### ISSUE TITLE
Error at run

### ISSUE THREAD

**Issue by fredvs** [bugaevc/writing-wayland-clients#3]
Hello.

I try to run your demo on Ubuntu 22.04  Wayland.

Compilation with _make_ is ok.
But at running/loading, there is a crash with that error:

```
 $ /home/fred/wayland-demo-c/runme
fish: Job 1, '/home/fred/wayland-demo-c/runme' terminated by signal SIGSEGV (Address boundary error)

```

**Comment by fredvs** [comment]
Note that with the Pascal translation + added debug code of your last demo 'The complete code' of the book, I am blocked in _registry_global_handler_ by 

```
shell = wl_registry_bind(registry, name,
            &wl_shell_interface, 1);
```

The result is always shell = nil.

(But _compositor_ and _shm_ are ok).

The crash appears when calling:

`struct wl_shell_surface *shell_surface = wl_shell_get_shell_surface(shell, surface);`

I suppose it is because shell = nil.

**Comment by bugaevc** [comment]
Hi again 🙂

Yes. The book was written back in 2017, and the Wayland landscape has changed a bit since then. While most of the things said are still relevant, some things need updates. For example, xdg-shell is no longer unstable (and the whole concept of unstable-ness is now less pronounced), and `wl_shell` support has been removed from the major compositors. You can see that the book mentions that it's deprecated, but I never expected that it will be unimplemented, and still think that was the wrong move, and my own Wayland compositor [will keep supporting `wl_shell`](https://github.com/owl-compositor/owl/blob/tmp/Sources/Shell/OwlWlShellSurface.m).

So I'm afraid you're going to have to jump straight to the [xdg-shell page](https://bugaevc.gitbooks.io/writing-wayland-clients/content/beyond-the-black-square/xdg-shell.html).

**Comment by fredvs** [comment]
Hello.

I finally found a C demo source using xdg that compiles and run:
https://wayland-book.com/

The translation into Pascal was hard but is ok:
https://github.com/fredvs/wayland-pascal/tree/main/src

Many thanks for your attention and tips.

![wylandclient_xdg_chessboard](https://github.com/bugaevc/writing-wayland-clients/assets/3421249/a697efd6-7e12-4d85-8ce9-745e5ec93a5f)
